name: napari_image_main
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.12.2
  - pytorch=2.3.1
  - torchvision=0.18.1
  - pytorch-lightning=2.3.3
  - matplotlib=3.9.1
  - tensorboard=2.17.1
  - scikit-image=0.22.0
  - scikit-learn=1.5.1
  - scipy=1.11.4
  - jsonargparse
  - pip=24.0
  - ipykernel # for jupyter notebook
  - lightning=2.3.3
  - joblib # For parallel runs, RF.
  - lightning[pytorch-extra] # For LightningCLI
  - pandas # For data manipulation vers 2.2.2